# Generated by Django 5.0.3 on 2024-03-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(verbose_name='fecha de modificación')),
                ('fecha_publicacion', models.DateTimeField(verbose_name='fecha de publicación')),
            ],
        ),
    ]
