# Generated by Django 4.1.7 on 2024-04-06 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("columna", "0001_initial"),
        ("notas", "0002_remove_nota_fecha_creacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="columna",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="columna.columna",
            ),
            preserve_default=False,
        ),
    ]
