# Generated by Django 4.1.7 on 2024-04-06 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tablero", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Columna",
        ),
    ]
